version: '3.8'

services:
  dbpostgresql:
    container_name: postgres_gnoss
    image: postgres:13.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gnoss         #<<Indicamos nuestro usuario>>#
      POSTGRES_PASSWORD: gnoss1234 #<<Indicamos nuestra contraseña>>#
      POSTGRES_DB: db_gnoss        #<<Indicamos nuestra base de datos>>#
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
